#!/bin/bash
user=$(eval getent passwd {$(awk '/^UID_MIN/ {print $2}' /etc/login.defs)..$(awk '/^UID_MAX/ {print $2}' /etc/login.defs)} | cut -d: -f1)
sed -i "s/eike/$user/g" "/etc/systemd/system/meteosat.service"
chown root:root /etc/systemd/system/meteosat.*
systemctl start meteosat.timer
systemctl enable meteosat.timer
